---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: vauxite-svr
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cayo
#base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
#image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: module-recipes/files.yml
  - from-file: module-recipes/default-flatpaks.yml
  - from-file: module-recipes/gnome-extensions.yml
  - from-file: module-recipes/icons.yml
  - from-file: module-recipes/starship-config.yml
  - from-file: module-recipes/wallpaper.yml
  - from-file: module-recipes/gschema-overrides.yml
  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully